---
default: &default
  example:
    item_file: "example_items.csv"
    answers_file: "example_answers.csv"
  depth_first_money_taxonomy_untagging:
    item_file: "depth_first_taxon_untag_items.csv"
    answers_file: "untag_taxon_answers.csv"
  depth_first_money_taxonomy_retagging_1:
    item_file: "depth_first_content_to_retag_Money_items_1.csv"
    answers_file: "retag_taxon_answers.csv"
  depth_first_money_taxonomy_retagging:
    item_file: "depth_first_content_to_retag_Money_items.csv"
    answers_file: "retag_taxon_answers.csv"
  depth_first_money_taxonomy_retagging_100:
    item_file: "depth_first_content_to_retag_Money100_features_items.csv"
    answers_file: "retag_taxon_answers.csv"
  logistic_regression_retag_dynamic_feature_count:
    answers_file: "retag_taxon_answers.csv"
    item_file: "depth_first_content_to_retag_Money_dynamic_feature_count_features_items.csv"
  untag_parenting:
    item_file: content_for_human_verification_to_untag_Parenting, childcare and children's services _items.csv
    answers_file: "untag_taxon_answers.csv"
  retag_going_being_abroad:
    item_file: content_to_retag_Going and being abroad_items.csv
    answers_file: "retag_taxon_answers.csv"
  retag_entering_staying_uk:
    item_file: content_to_retag_Entering and staying in the UK_items.csv
    answers_file: "retag_taxon_answers.csv"
  retag_education:
    item_file: content_to_retag_Education, training and skills_items.csv
    answers_file: "retag_taxon_answers.csv"
  untag_going_being_abroad:
    item_file: content_for_human_verification_to_untag_Going and being abroad_items.csv
    answers_file: "untag_taxon_answers.csv"
  untag_corporate_information:
    item_file: content_for_human_verification_to_untag_Corporate information_items.csv
    answers_file: "untag_taxon_answers.csv"
  untag_entering_staying_uk:
    item_file: content_for_human_verification_to_untag_Entering and staying in the UK_items.csv
    answers_file: "untag_taxon_answers.csv"
  untag_education:
    item_file: content_for_human_verification_to_untag_Education, training and skills_items.csv
    answers_file: "untag_taxon_answers.csv"
  retag_parenting:
    item_file: content_to_retag_Parenting, childcare and children's services _items.csv
    answers_file: "retag_taxon_answers.csv"

development:
  <<: *default

production:
  <<: *default
