---
default: &default
  example:
    item_file: "example_items.csv"
    answers_file: "example_answers.csv"
  money:
    answers_file: "retag_taxon_answers.csv"
    item_file: "depth_first_content_to_retag_Money_dynamic_feature_count_features_items.csv"


development:
  <<: *default

production:
  <<: *default
